#! /bin/bash
sudo apt install xorg xserver-xorg xutils mesa-utils xinit  firmware-linux-nonfree dmenu nitrogen firefox-esr thunar  git vim libx11-dev libxft-dev libxinerama-dev build-essential fonts-font-awesome compton wget curl git vim pulseaudio pavucontrol alsa-utils aptitude pulsemixer brightnessctl fish thunderbird virt-manager qemu-kvm
